site_name: Apprendre à programmer
theme: 'material'
site_author: 'El Gadjo Ridículo'
site_url: 'http://elgadjo.github.io/apprendre-a-programmer'

copyright: 'Copyright (c) 2016 El Gadjo Ridículo'

repo_name: 'GitHub'
repo_url: 'https://github.com/elgadjo/apprendre-a-programmer'

extra:
  palette:
    primary: 'deep purple'
    accent: 'orange'
  i18n:
    prev: 'Chapitre précédent'
    next: 'Chapitre suivant'

extra_css: [extra.css]

#author:
#  github: 'elgadjo'
#  twitter: 'elgadjo'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

pages: 
- 'Accueil': index.md
- '01. Généralités': 01-generalites.md
- '02. Généralités (partie 2)': 02-algorithmique.md
- '03. Algorigrammes' : 03-algorigrammes.md
- '04. Algorigrammes (partie 2)' : 04-instructions.md
- '05. Algorigrammes (partie 3)' : 05-instructions.md
