site_name: Apprendre à programmer
theme: 'material'
site_author: 'El Gadjo Perspicaz'
site_url: 'http://elgadjo.github.io/apprendre-a-programmer'
site_email: 'el.gadjo.perspicaz@gmail.com'

copyright: 'Copyright (c) 2016 El Gadjo Perspicaz'

repo_name: 'GitHub'
repo_url: 'https://github.com/elgadjo/apprendre-a-programmer'

extra:
  palette:
    primary: 'deep purple'
    accent: 'orange'

author:
  github: 'elgadjo'
  twitter: 'elgadjo'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

pages: 
- 'Accueil': index.md
- '01. Généralités': 01-generalites.md
- '02. Généralités (suite)': 02-algorithmique.md
